import {
  Dialog,
  Autocomplete,
  Menu,
  Submenu,
  MenuItem,
  MenuItemGroup,
  Input,
  InputNumber,
  Radio,
  RadioGroup,
  RadioButton,
  Checkbox,
  CheckboxButton,
  CheckboxGroup,
  Switch,
  Button,
  ButtonGroup,
  Table,
  TableColumn,
  DatePicker,
  Popover,
  Form,
  FormItem,
  Alert,
  Icon,
  Row,
  Col,
  Upload,
  Badge,
  Image,
} from 'element-ui'
import 'element-ui/lib/theme-chalk/index.css'

export default function(app) {
  app.use(Dialog)
  app.use(Autocomplete)
  app.use(Menu)
  app.use(Submenu)
  app.use(MenuItem)
  app.use(MenuItemGroup)
  app.use(Input)
  app.use(InputNumber)
  app.use(Radio)
  app.use(RadioGroup)
  app.use(RadioButton)
  app.use(Checkbox)
  app.use(CheckboxButton)
  app.use(CheckboxGroup)
  app.use(Switch)
  app.use(Button)
  app.use(ButtonGroup)
  app.use(Table)
  app.use(TableColumn)
  app.use(DatePicker)
  app.use(Popover)
  app.use(Form)
  app.use(FormItem)
  app.use(Alert)
  app.use(Icon)
  app.use(Row)
  app.use(Col)
  app.use(Upload)
  app.use(Badge)
  app.use(Image)
}
